In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
prd = pd.read_csv('/content/drive/MyDrive/prediction.csv')
prd.describe()

,Year,Temperature Change,GHG emissions: gross,"Climate related disasters frequency, Number of Disasters: TOTAL",Change in mean sea level: Sea level: TOPEX.Poseidon,Unnamed: 5,Unnamed: 6,Unnamed: 7
count,33.00000,33.000000,33.000000,33.000000,33.000000,0.0,0.0,0.0
mean,2006.00000,0.474515,76.557121,1.151515,16.732727,NaN,NaN,NaN
std,9.66954,0.482775,5.251707,1.003781,27.160801,NaN,NaN,NaN
min,1990.00000,-0.716000,65.196981,0.000000,-24.880000,NaN,NaN,NaN
25%,1998.00000,0.125000,73.576262,0.000000,-2.880000,NaN,NaN,NaN
50%,2006.00000,0.544000,78.503950,1.000000,16.960000,NaN,NaN,NaN
75%,2014.00000,0.912000,80.482572,2.000000,36.100000,NaN,NaN,NaN
max,2022.00000,1.319000,82.832552,4.000000,62.280000,NaN,NaN,NaN